image: gradle:jdk21

stages:
  - test
  - build

Test:
  stage: test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  script:
    - gradle test jacocoTestReport
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: build/reportsJaCoCo/test/jacocoTestReport.xml

Code coverage:
  stage: test
  image: haynes/jacoco2cobertura:latest
  script:
    - python /opt/cover2cover.py build/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/kotlin/ > build/cobertura.xml
  needs: ["Test"]
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: build/reportsJaCoCo/test/coverage.xml

Build using Gradle:
  stage: build
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle
  script:
    - ./gradlew --build-cache assemble

Build and push Docker image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_TOKEN" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: always
    - when: never
