image: gradle:jdk21

stages:
  - build
  - test

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/
    - build/

build:
  stage: build
  script:
    - ./gradlew build
  only:
    - branches

test:
  stage: test
  script:
    - ./gradlew test
  only:
    - branches
