ktor:
  application:
    modules:
      - cz.cvut.fit.atlasest.application.ApplicationKt.module
  deployment:
    port: 8080
    host: "0.0.0.0"
    rootPath: "/api"

data:
  fileName: "db.json"
  identifiersFileName: "identifiers.json"

cors:
  allowed-host: *

pagination:
  defaultLimit: 10
