ktor:
  application:
    modules:
      - cz.cvut.fit.atlasest.application.ApplicationKt.module
  deployment:
    port: 8080
    host: localhost
    rootPath: "/api"

data:
  fileName: "db.json"
  identifiersFileName: "identifiers.json"