ktor:
  application:
    modules:
      - cz.cvut.fit.atlasest.application.ApplicationKt.module
  deployment:
    port: 8080
    host: "0.0.0.0"
    rootPath: "/api"

data:
  collectionsFilename: "db.json"
  identifiersFilename: "identifiers.json"

cors:
  allowed-host: *
